# Generated by Django 4.0.3 on 2023-02-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='specialzation',
            field=models.CharField(default='cardio', max_length=100),
            preserve_default=False,
        ),
    ]
