# Generated by Django 4.0.3 on 2023-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_doctors_specialzation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.ImageField(default='image', upload_to='media/'),
            preserve_default=False,
        ),
    ]
